export const __DEV__ = import.meta.env.MODE === "development";
export const appName = import.meta.env.APP_NAME;
export const appVersion = import.meta.env.APP_VERSION;
export const appDescription = import.meta.env.APP_DESCRIPTION;
export const appDefaultLocalCode = import.meta.env.APP_DEFAULT_LOCAL_CODE;
export const appFallbackLocalCode = import.meta.env.APP_FALLBAK_LOCAL_CODE;
export const appCodeName = import.meta.env.APP_CODE_NAME;
export const appDefaultDirection = import.meta.env.APP_DEFAULT_DIRECTION;
export const appProductionBasePath = import.meta.env.APP_BASE_BATH;
export const app = import.meta.env.APP_NAME;
